### ISSUE TITLE
suggestion to use linear 10k potentiometer

### ISSUE THREAD

**Issue by Rappelbox** [Jerware/PinSim#1]
The idea is to use 10k linear potentiometer instead of the sharp sensor as they are more common available, cheap and there are several commercial and open source controllers already using this aproach.

A direct 12/16bit analog read and code simplification could be achieved as well.

BTW, this is a nice little controller :)

Greetings
Dom

**Comment by Jerware** [comment]
Thanks. I looked into that but decided the solid state aspects of the Sharp sensor were worth the cost. E.g. reliability, no flutter, more accurate feel.
