### ISSUE TITLE
GPIO 21 and 23 don't appear to be mapped.  13 and 14 mapped to analog instead of buttons 9 and 10

### ISSUE THREAD

**Issue by WindRaidor** [Jerware/PinSim#4]
I'll admit, that I could be mis-interpreting things.  But, I am using the latest pinsim.hex file and everything is working except for my magna save flippers.  My left and right second set of flippers are wired to the GPIO board on the Pinsim board.  I originally tried 13 and 14.  But, those get mapped to an analog axis which visual pinball doesn't let me map to left and right magnasaves.  And I thought I read in the readme that 13 and 14 are supposed to be mapping across as buttons 9 and 10 on an xbox controller.  If that were the case everything would be great.  I tried changing the wiring to GPIO 21 and 23, hoping I would see a difference.  But those appear to be completly unmapped to the xbox 360 controller bindings.

Suggestion would be to allow for the magnasave flippers to be mapped to buttons 9 and 10 on an xbox controller interface, not the analog axis, so that visual pinball will allow me to map those appropriately.

**Comment by Jerware** [comment]
It's been awhile since I looked at the code, but it appears you're right. GPIO 21 & 23 were being used to test special analog buttons, and they are totally disabled. I could map those to buttons 9 & 10. Would that work for you? I don't want to mess with GPIO 13 & 14, since that solution appears to work for people.

**Comment by Jerware** [comment]
Change pushed. Let me know if that works for you.

**Comment by WindRaidor** [comment]
Works great!  Thanks for that quick response.  One other question...for the plunger, it doesn't appear that there is incremental progress reported back when someone pulls back on the plunger (rY Axis).  Its an all or none thing.  Im looking at it through Windows USB Controller configuration for the xbox 360 controller PinSim is presenting itself as.  I've calibrated several times successfully too.  Wondering if that portion of the code is working or not.  If you want me to open a new issue, let me know.

**Comment by Jerware** [comment]
The plunger should report back constantly, and move the "Y Rotation" axis out and in. It works for me with this latest firmware, so I suspect something is amiss with your setup.

**Comment by WindRaidor** [comment]
Found it...i hadn't calibrated the joystick in Windows.  Once I did that, the Y axis was adjusted properly and picking up on things.  Closing this issue out, and appreciate the confirmation on the plunger working to help me zero in on the issue.
