### ISSUE TITLE
rumbelers causing controller to disconnect

### ISSUE THREAD

**Issue by jrl0516** [Jerware/PinSim#6]

**Comment by jrl0516** [comment]
sorry new to github I was wondering my arcade buttons came with led light but am i pulling to much power? every time the rumbelers start working the fx3 gives me a reconnect controller code

**Comment by Jerware** [comment]
Yes, your USB host is not providing amble power, or the rumble motors & LEDs are pulling too much.

**Comment by jrl0516** [comment]
So after disconnecting all leds and still getting same problem i disconnected the rumblers one at a time i find that the large rumbler is causing it to disconnect the rumbler works it must just cause some sort of short i guess ill be ordering another one because thats the best part of the controller is the feed back i will let you know if that fixes it. Also thank you for the work you put into this its one of the best things ive seen for virtual pinball ever

**Comment by jrl0516** [comment]
replacing the rumbler fixed the problem of the controller connection thank you for your help my brother is going to love this thing
